language: python
python:
 - "2.7"
 - "3.4"
install:
- python setup.py develop
script: python setup.py test
notifications:
    email: false
    irc:
        - "irc.freenode.net#fedora-apps"
    on_success: change
    on_failure: change
